#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
# bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding 0
bspc config top_padding 56


bspc config normal_border_color           "#4c566a" 
bspc config active_border_color	      "#1e1e1e" 
bspc config focused_border_color	      "#5e81ac" 
bspc config presel_feedback_color	      "#5e81ac" 
bspc config urgent_border_color 	      "#dd2727"
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

feh --bg-fill ~/blue-sky/wallpapers/blue3.png

#Autostart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
#dunst &
~/.config/polybar/launch.sh
polybar example &

